# See https://pre-commit.com for more informatons
# See https://pre-commit.com/hooks.html fo more hooks

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-json
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["--line-length", "79"]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        language: python
        args:
          - -r
          - -lll
          - ./app/

  - repo: local
    hooks:
      - id: create requirements
        name: create requirements
        entry: sh hooks/write_requirements.sh
        language: system
        always_run: true
        pass_filenames: false
